### ISSUE TITLE
Watch later button missing

### ISSUE THREAD

**Issue by Wielder4201** [dschil138/better-youtube-hover-play#2]
Top right "Watch later" and "Add to playback queue" buttons on the video thumbnail don't appear when the extension is set to disable all previews.

![Screenshot 2023-11-24 135232](https://github.com/dschil138/better-youtube-hover-play/assets/149764921/fe355eac-f8e6-4a03-b5b8-06e60893fbf9)        ![Screenshot 2023-11-24 151405](https://github.com/dschil138/better-youtube-hover-play/assets/149764921/dd9dc8ab-e16f-4aed-98a7-443af19cc859)

**Comment by dschil138** [comment]
Hey sorry for some reason I never got a notification about this, just now seeing it.

I will look into this. I'm actually not sure there will be a solution for this that is feasible for me to implement, but if I can, I will definitely add it.

**Comment by dschil138** [comment]
Hey @Wielder4201 I was actually able to find a workaround for this and got it implemented. The update got accepted by the chrome store this morning, so if you're still using the extension you should get it soon.

I'm going to close this issue but if you find any bugs or anything please let me know!
